variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_SSL_NO_VERIFY: "1"

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test