variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_SSL_NO_VERIFY: "1"

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd music_individual
    - .\gradlew assemble

test:
  stage: test
  script:
    - cd music_individual
    - .\gradlew test

sonarqube:
  stage: .post
  script:
    - cd music_individual
    - .\gradlew sonarqube